### ISSUE TITLE
Parses all rows instead of only the ones with data

### ISSUE THREAD

**Issue by ThomasTJdev** [xflywind/xlsx#3]
1) Have Excel file with data in row 1-100
2) Enable filter for top column (row 1)
3) Sort ASC on a specific column "XYZ", e.g. row 2-10 now has data in "XYZ", while row 11-100 is blank.
4) Manually delete row 11-100. Now the last row is row 10.
5) Parse Excel file with xlsx-lib results in all rows (also the empty ones) which is 1048575

## Test
I have attached a copy of the Excel file, where I have performed the actions above.
[fine.xlsx](https://github.com/xflywind/xlsx/files/4109181/fine.xlsx)

Same problem also arise with toCsv.

```nim
import xlsx

let sheetName = "Cx"
let data = parseExcel("fine.xlsx")
let rows = data[sheetName].toSeq(true)
echo rows.len
# result   = 1048575
# expected = 10
```

**Comment by xflywind** [comment]
Thanks for your help! @ThomasTJdev 
![image](https://user-images.githubusercontent.com/43030857/73115693-95291b00-3f64-11ea-9908-a8b1637fcdde.png)
Because Metadata shows that the dimensions are A1:D1048576. Maybe parseExcel should support eliminating empty rows.You can use iterator `lines`, which can ignore empty lines.

**Comment by ThomasTJdev** [comment]
Ahh I see - thanks @xflywind!

> Maybe parseExcel should support eliminating empty rows.

Well, that would solve my current problem :) but I think it should keep the empty rows as standard - what if the user uses an empty row to separate data?

Maybe a "stop parsing after n-empty lines"-param could be implemented.
```nim
proc parseExcel*(fileName: string, sheetName = "", header = false,
    skipHeaders = false, escapeStrings = false, maxEmptyRows = 10): SheetTable =
  ## When it is registrered that there's more than `maxEmptyRows` (empty rows) right
  ## after each other, the parsing will stop. This is a fallback if the spreadsheets
  ## dimensions are wrong, e.g. `dimensions ref="A1:D1048576"`. I you wants to
  ## parse the whole spreadsheet, you can just set it `maxEmptyRows=1048576`.
```

The `lines` iterator does not fix it for me, it still prints all the empty rows.
```nim
for i in lines("fine.xlsx", "Cx"):
  echo i
```

**Comment by xflywind** [comment]
iterator lines(fileName: string; sheetName: string; escapeStrings = false;
              skipEmptyLines = false): string {...}

**Comment by ThomasTJdev** [comment]
Thanks - my mistake. The iterator `lines` works fine, but if I need the data in CSV or seq format, I need to reimplement `toCsv` and `toSeq` inside the iterator `lines` - otherwise it just `yields` the data.

Would you be interested in a PR, where `skipEmptyLines` is a param for `toSeq`?
```nim
proc toSeq*(s: SheetArray, skipHeaders = false, skipEmptyLines = false): seq[seq[string]] {.inline.} =
  ## Parse SheetArray and return a seq[seq[string]]
  runnableExamples:
    let sheetName = "Sheet2"
    let data = parseExcel("tests/test.xlsx")
    let rows = data[sheetName].toSeq(false)
    for row in rows:
      echo row

  let
    sheet = s.data
    (_, cols) = s.shape
  var
    cCount = 1
    firstRow = true
    row: seq[string]
  # Loop through sheet
  for r in sheet:
    # Check is headers should be included
    if skipHeaders and firstRow:
      # If last column end header loop
      if cCount == cols:
        firstRow = false
        cCount = 0
      cCount += 1
      continue


    if skipEmptyLines and len(r) == 0: # <= Check for empty lines
      continue


    # Add data to internal seq[string]
    row.add(r)
    # Add internal seq[string] to result var
    if cCount == cols:
      cCount = 1
      result.add(row)
      row = @[]
    else:
      cCount += 1
```

**Comment by xflywind** [comment]
Thanks. @ThomasTJdev 
I will add `skipEmptyLines` params in `parseExcel` using lines which can save some space.

**Comment by xflywind** [comment]
Thanks for your help.@ThomasTJdev 
Now parseExcel support skip empty lines.

**Comment by xflywind** [comment]
@ThomasTJdev 
I have changed params from `skipEmptyLines` to `trailing`, because It only eliminating empty lines according to the last element's line number.

**Comment by ThomasTJdev** [comment]
> @ThomasTJdev
> I have changed params from `skipEmptyLines` to `trailing`, because It only eliminating empty lines according to the last element's line number.

I'm not sure, that I understand - can you detail 'empty lines according to the last element's line number'. Trailing brings my thought to std lib strutils, where you have trailing spaces, while I don't see the connection between an empty row and trailing.

**Comment by xflywind** [comment]
Sorry for my poor English.
for example, if last row with element is tenth line, empty lines after tenth line will be skipped.But if there are empty lines before tenth line, these lines will be reserved.And the length of sequence is ten.

If you want to skip all empty lines, you should use `lines`.

**Comment by ThomasTJdev** [comment]
No problem, your english is fine.

Okay, now I get it. That's a much better solution, cause you'll keep the users spreadsheet structure. Regarding the name `trailing` is fine, but you should include your description from https://github.com/xflywind/xlsx/issues/3#issuecomment-578464907 in the docs. If you were to go for another name, I would suggest `trailingRows` to indicate, that it is the trailing rows.

PS - version 0.4.2 has not been release, the latest is 0.4.0.

**Comment by xflywind** [comment]
Thanks for your advice.I rename it `trailingRows` and release a new version.
