### ISSUE TITLE
How can i write to excel file?

### ISSUE THREAD

**Issue by whydee86** [xflywind/xlsx#5]
Hi, I am using this module, but I can't figure out how to write to excel file and not only read from him, for example, how I can edit a specific sheet?

**Comment by xflywind** [comment]
Sorry, It doesn't support write xlsx, but instead you can use 

https://github.com/KeepCoolWithCoolidge/nimlibxlsxwriter

**Comment by whydee86** [comment]
> 
> 
> Sorry, It doesn't support write xlsx, but instead you can use
> 
> https://github.com/KeepCoolWithCoolidge/nimlibxlsxwriter

It is not working, I installed the module and setup but I the nim doesn't recognise the module and the functions. Maybe you can help me?

**Comment by ThomasTJdev** [comment]
> > Sorry, It doesn't support write xlsx, but instead you can use
> > https://github.com/KeepCoolWithCoolidge/nimlibxlsxwriter
> 
> It is not working, I installed the module and setup but I the nim doesn't recognise the module and the functions. Maybe you can help me?

Hi @whydee86 

Checkout this PR https://github.com/KeepCoolWithCoolidge/nimlibxlsxwriter/pull/12 . Could you try that and comment on it in nimlibxlsxwriter-repo?
