### ISSUE TITLE
Error: unhandled exception: key not found: sheet1 [KeyError]

### ISSUE THREAD

**Issue by whiterock** [xflywind/xlsx#6]
Minimal breaking example:
```nim
for i in lines("test.xlsx", "Anlageuniversum"):
    echo i
```
and the file can be downloaded from https://wikifolio.blob.core.windows.net/prod-documents/Investment_Universe.de.xlsx

The full error message is
```
/Users/whiterock/.nimble/pkgs/xlsx-0.4.4/xlsx/utils.nim(996) wikifolio
/Users/whiterock/.choosenim/toolchains/nim-1.4.2/lib/pure/collections/tables.nim(262) []
Error: unhandled exception: key not found: sheet1 [KeyError]
```
I did add three debug echos in your lines iterator as follows
```nim
  echo $contentTypes
  echo $workbook
  echo $styles
```
which outputs
```nim
{"workbook": "xl/workbook.xml", "sheet2": "/xl/worksheets/sheet2.xml", "styles": "/xl/styles.xml"}
(data: {"Anlageuniversum": "1"}, date1904: false)
@[]
```
This illustrates where the problem lies. Since the value for the key Anlageuniversum is 1 it looks for sheet1 but there ∃ only a sheet2, however I can see no error on my part, since I checked that Anlageuniversum ∃ before with another proc in your library.

Thanks in advance,
whiterock

**Comment by ThomasTJdev** [comment]
Confirmed. The file breaks the parsing. If you open and re-save the file as an `xlsx` again the size will increase x2, but then it is parsable.

**Code**
```nim
import xlsx
let xlsxData = parseExcel("Investment_Universe.de.xlsx", trailingRows=false)
```

**Comment by whiterock** [comment]
> Confirmed. The file breaks the parsing. If you open and re-save the file as an `xlsx` again the size will increase x2, but then it is parsable.
> 
> **Code**
> 
> ```nim
> import xlsx
> let xlsxData = parseExcel("Investment_Universe.de.xlsx", trailingRows=false)
> ```

Thanks for confirming. Unfortunately this workaround is impractical for me as I need to fetch the resource periodically and programmatically.

Let‘s hope the author or someone knowledgable of xlsx is able to fix this 👍

**Comment by xflywind** [comment]
It's easy to make a workaround,
```nim
iterator lines*(fileName: string, index: int,
    escapeStrings = false, skipEmptyLines = false): string =
  extractXml(fileName)
  defer: removeDir(TempDir)
  let
    contentTypes = parseContentTypes(TempDir / "[Content_Types].xml")
    workbook = parseWorkBook(TempDir / contentTypes["workbook"])
    styles = parseStyles(TempDir / contentTypes["styles"])

  var sharedString: SharedStrings
  if "sharedStrings" in contentTypes:
    sharedString = parseSharedString(TempDir / contentTypes["sharedStrings"],
        escapeStrings = escapeStrings)

  var
    sheet = parseSheet(TempDir / contentTypes["sheet" & $index], styles,
        workbook.date1904)

  for item in get(sheet, sharedString):
    if skipEmptyLines and len(item) == 0:
      continue
    yield item
```

However this library parses everything into memory which makes it unable to parse big files.

**Comment by artemklevtsov** [comment]
It may be fixed using the `xl/_rels/workbook.xml.rels`:
1. find `r:id` from the `xl/workbook.xml` by `name`
2. find `Target` from the `xl/_rels/workbook.xml.rels` by `Id`

**Comment by xflywind** [comment]
Should be fixed by https://github.com/xflywind/xlsx/pull/8
