### ISSUE TITLE
unrelated errors when importing module

### ISSUE THREAD

**Issue by arkanoid87** [xflywind/xlsx#7]
seems that xlsx is messing with standard module namespaces somehow

see
https://play.nim-lang.org/#ix=2U4z

nim 1.4.4

**Comment by xflywind** [comment]
Known issues:
https://github.com/nim-lang/Nim/issues/7322

**Comment by xflywind** [comment]
workaround
`import xlsx except toSeq`, then you still use `xlsx.toSeq`.
